### PR TITLE
Move README examples into sub directory

### PR DESCRIPTION
**Pull request by eiri**
## PR summary

Moves embedded examples into `test` sub directory for consistency with the rest of SDKs and as a preparation for managed examples.

Fixes: <! -- link to issue -->

**Note: An existing issue is [required](https://github.com/IBM/cloudant-go-sdk/blob/master/CONTRIBUTING.md#PRs) before opening a PR.**

## PR Checklist

Please make sure that your PR fulfills the following requirements:

- [x] The commit message follows the
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [x] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by eiri** [comment]
Changes of automation for README.md  done in a separate PR and pending merge of this one.

**Comment by eiri** [comment]
Preview of PR to confirm that embedded examples are not broken: https://github.com/IBM/cloudant-go-sdk/tree/move-readme-examples

**Review by ricellis — APPROVED** [review]
I think you're going to see some whitespace changes when the auto-updated README follows-on, but it shouldn't be an issue.

**Comment by eiri** [comment]
> I think you're going to see some whitespace changes when the auto-updated README follows-on, but it shouldn't be an issue.

yeah, auto-trimmer kicked in and I thought it's better to fix it instead of fighting with it. I'll check not to reintroduce it in follow-up automation change.

**Pull request merged**
