### PR TITLE
Switch header checks to regex

### PR DESCRIPTION
**Pull request by bessbd**
## PR summary

The header checks right now are using exact text matches which is not flexible.

This commit refactors that check into a regex check so that it becomes more flexible.
## PR Checklist

Please make sure that your PR fulfills the following requirements:

- [x] The commit message follows the
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features) - N/A
- [ ] Docs have been added / updated (for bug fixes / features) - N/A

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?
See above.

## What is the new behavior?
See above.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by eiri** [comment]
Two questions - where is `{{YEAR}}` var coming from? Is that regexp in linter's config capturing or just matching?

**Comment by bessbd** [comment]
> Two questions - where is `{{YEAR}}` var coming from? Is that regexp in linter's config capturing or just matching?

Good questions!
- `{{YEAR}}` is described in https://github.com/IBM/cloudant-go-sdk/pull/69/files#diff-6179837f7df53a6f05c522b6b7bb566d484d5465d9894fb04910dd08bb40dcc9R23 . (See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml#L215 or https://github.com/denis-tingajkin/go-header/blame/master/README.md#L26 for further reference.)
- Why is the capture important here? (Btw, I think it's match only.)

**Comment by eiri** [comment]
So `header-template.txt` is not a template to fill, but template to compare with? Got it. 

If it's just match, then `/20\d{2}/` would do the same as your current regex, but will be easier to read

**Comment by bessbd** [comment]
> So `header-template.txt` is not a template to fill, but template to compare with? Got it.
> 
> If it's just a match, then `/20\d{2}/` would do the same as your current regex, but will be easier to read

Do you mean like in 463f192 ?

**Comment by eiri** [comment]
No, I mean literally `YEAR: "20\\d{2}"`. 

I suspect you are expecting the second part of your regex to validate stuff like `2020, 2021` and prevent typos like `2020, duh!`, but it actually doesn't. Since the second part is optional, as long as `YEAR` start with 20\d{2} regexp passes the match. Basically this is why I asked if it's matching of capturing, because I initially though that the lintier somehow can extract year and pass it to the header's template.

It's possible to write strict regex here, but totally not worth it, to be honest, given how often headers changed and we do human reviews anyway.

**Comment by bessbd** [comment]
> I suspect you are expecting the second part of your regex to validate stuff like 2020, 2021

I do expect it to do that.

> and prevent typos like 2020, duh!, but it actually doesn't

It does seem to work fine on my machine:
```
[donat:~/cloudant-go-sdk] 463f192(+1/-1) 6m30s ± golangci-lint run
common/version.go:1:33: Actual: , foo. All Rights Reserved.
Expected:. All Rights Reserved. (goheader)
// © Copyright IBM Corporation 2020, foo. All Rights Reserved.
```
for a change such as
```diff
diff --git a/common/version.go b/common/version.go
index 9859d80..2201693 100644
--- a/common/version.go
+++ b/common/version.go
@@ -1,4 +1,4 @@
-// © Copyright IBM Corporation 2020. All Rights Reserved.
+// © Copyright IBM Corporation 2020, foo. All Rights Reserved.
 //
 // Licensed under the Apache License, Version 2.0 (the "License");
 // you may not use this file except in compliance with the License.
```
. Am I missing something here?


> Since the second part is optional

I'm not a lawyer and I can't argue with any legal guidelines. This is the convention we've been using internally and this is the format we've agreed on previously. If you have any concerns and you believe it's worth blocking this change (and potentially changing this over our other repos for maintainability), please let me know.

**Review by vmatyusGitHub — APPROVED** [review]

**Comment by vmatyusGitHub** [comment]
Just get an idea from python:
Is that possible to extend the regexp to match also files that are excluded from lint like: 
cloudant_v1, cloudant_v1_test, cloudant_v1_suite_test: Those has `Copyright IBM Corp. 2021.`
What other files use: `© Copyright IBM Corporation 2020. All Rights Reserved.`
What do you think?

**Comment by eiri** [comment]
@bessbd 

> Am I missing something here?

You are missing that judging by your output the linter doesn't use matching, as your said, but substitution - note the missing year. Matching doesn't work - https://regex101.com/r/CibReT/2/, but capturing and comparing the rest of output with a static text, as linter seems to be doing, naturally does.

> I'm not a lawyer and I can't argue with any legal guidelines. 

Nobody said anything about legals, you are misinterpreting my comment. I'm not saying `2020, duh!` is valid format, I'm saying that making this type of mistake unintentionally has rather low probability (and even less probable for once in a year change) and will be noticed in human review.

Your regex is complex and its intent is confusing. Complexity has price in maintainability. I pity poor soul that'd write `2020,  2021`, get stopped by linter, because of the two spaces and will try to understand what's going on. If it's possible to simplify something it should be simplified, that's pretty much nature of my comment.

> If you have any concerns and you believe it's worth blocking this change 

I'm +0 on the change as it is right now, with the rational I just described.

**Review by vmatyusGitHub — COMMENTED** [review]
LGTM +1

**Review by eiri — APPROVED** [review]

**Comment by bessbd** [comment]
Thank you for the review, @eiri and @vmatyusGitHub ! I'm about to merge this.

**Pull request merged**
